---
- hosts: localhost
  become: yes
  vars:
    - i3_use_gaps: true
    - i3_terminal: xfce4-terminal
    - i3_use_polybar: true
    - i3_optional: false
    - main_font: "robotomono"
  remote_user: kali
  become_user: kali
  become: true
  tasks:
  - name: Install Ansible Galaxy roles
    ansible.builtin.command:
      cmd: "ansible-galaxy install -r requirements.yml -p roles"
    delegate_to: localhost
    run_once: true
  - name: Install missing packages
    become: yes
    become_user: root
    apt:
      pkg:
        - i3-wm
        - i3lock
        - i3status
        - zsh
        - neovim
        - apt-file
        - htop
        - rofi
        - nodejs
        - nitrogen
      state: latest
      update_cache: yes
  - name: Install fonts and update font cache
    script: install_fonts.sh
    args:
      creates: /usr/share/fonts/truetype/robotomono
  - name: Set shell of user kali to zsh
    user:
      name: kali
      shell: /bin/zsh
  roles:
     - ansible-xresources
     - ansible-i3
     - ansible-vim
     - ansible-xfce4-terminal
     - ansible-tmux
     - ansible-zsh
     - ansible-rofi
